### ISSUE TITLE
Mysql errors

### ISSUE THREAD

**Issue by alvinwoon** [m5n/nutriana#2]
> ERROR 2 (HY000) at line 133: File '../data/FOOD_DES.txt.trimmed' not found (Errcode: 2 - No such file or directory)

So I renamed all the data files by removing trimmed and rerun it. That gives me

> ---
> 
> load data local infile '../data/FOOD_DES.txt'
>     into table FOOD_DES
>     fields terminated by '^' optionally enclosed by '~'

---

Thanks for the wonderful project btw. Yours is the most up-to-date, mysql NSDA port out there.

**Comment by m5n** [comment]
Hi Alvin,

Did you run the mysql command from the "dist" dir?
E.g. you're in "usda_nndsr/dist" and run "mysql ... < usda_nndsr_mysql.sql"

If you were in "usda_nndsr" and ran "mysq ... < dist/usda_nndsr_mysql.sql" then the error is expected.

If you are not able to run it, please also give me the MySQL version you're using.

**Comment by m5n** [comment]
Hmm, I noticed I did not check in the .trimmed files...

If the above suggestion does not work, please cd to the "nutriana/src" directory and run "./build.sh"
That should generate everything that's needed. Then go to the "dist" dir of the nutrient DB of your choice and run the "mysql ... < ..._mysql.sql" command from there. 

Looking forward to hearing if you are successful!

**Comment by m5n** [comment]
Sorry, just ignore what I said above. :)

I checked in the required files, so everything is available in the "dist" directory; no need to build anything.
Please sync or clone, cd to the "usda_nndsr/dist" and run "mysql ... < usda_nndsr_mysql.sql" 
That should do it!

**Comment by alvinwoon** [comment]
Thanks man!
